language: go

matrix:
  include:
    - go: 1.10.x

install:
  - go get github.com/mjibson/esc

script:
  - go build -o ./dist/esc github.com/mjibson/esc 
  
after_script:
  - cd ./dist
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Build bins"
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master:bins

env:
  global:
    - U_NAME: leitwolf
    - GH_REF: github.com/leitwolf/gobuilder.git
