language: go

matrix:
  include:
    - go: 1.13.x

install:
  - go get github.com/mjibson/esc
  - go get golang.org/x/tools/gopls

script:
  - mkdir bin
  - cd ./bin
  - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build github.com/mjibson/esc
  - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build golang.org/x/tools/gopls
  
after_script:
  - cd ./
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Build bins"
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}

env:
  global:
    - U_NAME: leitwolf
    - GH_REF: github.com/leitwolf/gobuilder.git
    - P_BRANCH: bin
